### PR TITLE
Added CC0 LICENSE for rules

### PR DESCRIPTION
**Pull request by shaunroselt**

### CODE REVIEW

**Comment by JaioCG** [comment]
why would just literal text need a software license LOL its not software

**Comment by shaunroselt** [comment]
> why would just literal text need a software license LOL its not software

Licenses aren't just for source code, but also there isn't just text in this repo.

**Comment by mlugg** [comment]
I think CC0 would be a better fit -- it covers the text of the rules more effectively, and we really need no restrictions even wrt crediting on this repo.

**Comment by shaunroselt** [comment]
> I think CC0 would be a better fit -- it covers the text of the rules more effectively, and we really need no restrictions even wrt crediting on this repo.

I took a look at the CC0 license. I agree. CC0 would be a better fit. I've changed it to CC0.

**Comment by mlugg** [comment]
Okay, so, boring legal nonsense: @ellzie, @ThisAMJ, @ThatFridgeFella -- y'all have contributed to this repo before, are you happy releasing your contributions under the CC0 license, which essentially constitutes waiving all copyrights on your contributions? 

(And just for clarity, I do consent to *my* contributions -- which are the bulk of this repo -- being licensed as such)

**Comment by ThisAMJ** [comment]
Sure!

**Comment by ellzie** [comment]
Sounds good

**Comment by ThatFridgeFella** [comment]
Yeah sure

**Pull request merged**
